import type { ProductWebsiteTechnicalAudit } from '@/types/product-website';

export interface ProductWebsiteTechnicalFileDraft {
  id: 'robots' | 'llms' | 'llms-full';
  filename: 'robots.txt' | 'llms.txt' | 'llms-full.txt';
  label: string;
  description: string;
  content: string;
}

interface BuildTechnicalFileDraftsInput {
  targetUrl: string;
  title?: string | null;
  description?: string | null;
  canonical?: string | null;
  technicalAudit?: ProductWebsiteTechnicalAudit | null;
}

function normalizeSiteUrl(value: string) {
  try {
    const url = new URL(value);
    return {
      origin: url.origin,
      pageUrl: url.toString(),
    };
  } catch {
    return null;
  }
}

function uniqueUrls(values: Array<string | null | undefined>) {
  return [...new Set(values.filter((value): value is string => Boolean(value)))];
}

export function buildProductWebsiteTechnicalFileDrafts({
  targetUrl,
  title,
  description,
  canonical,
  technicalAudit,
}: BuildTechnicalFileDraftsInput): ProductWebsiteTechnicalFileDraft[] {
  const site = normalizeSiteUrl(canonical || targetUrl);
  if (!site || !technicalAudit) return [];

  const siteTitle = title?.trim() || site.origin.replace(/^https?:\/\//, '');
  const siteDescription = description?.trim() || '请在发布前补充网站定位、核心产品与服务对象。';
  const knownPages = uniqueUrls([site.origin, canonical, targetUrl]);
  const pageLinks = knownPages
    .map((url, index) => `- [${index === 0 ? '网站首页' : `核心页面 ${index + 1}`}](${url})：请补充该页面的用途说明。`)
    .join('\n');
  const drafts: ProductWebsiteTechnicalFileDraft[] = [];

  if (technicalAudit.robots?.found === false) {
    drafts.push({
      id: 'robots',
      filename: 'robots.txt',
      label: 'robots.txt',
      description: '允许正常抓取并声明站点地图位置；发布前请与现有访问策略核对。',
      content: [
        '# Generated by GeniLink GEO Analysis — review before publishing',
        'User-agent: *',
        'Allow: /',
        '',
        `Sitemap: ${site.origin}/sitemap.xml`,
        '',
      ].join('\n'),
    });
  }

  if (technicalAudit.llms?.found === false) {
    drafts.push({
      id: 'llms',
      filename: 'llms.txt',
      label: 'llms.txt',
      description: '提供网站简介与已知核心页面，待负责人补充关键事实和联系方式。',
      content: [
        `# ${siteTitle}`,
        '',
        `> ${siteDescription}`,
        '',
        '## 核心页面',
        '',
        pageLinks,
        '',
        '## 关键事实',
        '',
        '- TODO：补充可公开验证的成立时间、服务范围、客户或产品数据。',
        '- TODO：补充品牌、产品和主体之间的准确关系。',
        '',
        '## 联系方式',
        '',
        '- TODO：补充官方联系页面或公开邮箱。',
        '',
      ].join('\n'),
    });
  }

  if (technicalAudit.llmsFull?.found === false) {
    drafts.push({
      id: 'llms-full',
      filename: 'llms-full.txt',
      label: 'llms-full.txt',
      description: '长版内容清单骨架，适合补充产品、案例、文档和资源页面。',
      content: [
        `# ${siteTitle}：完整内容指南`,
        '',
        `> ${siteDescription}`,
        '',
        '## 已检测页面',
        '',
        pageLinks,
        '',
        '## 产品与服务',
        '',
        '- TODO：逐项添加产品或服务页面的绝对 URL 与一句话说明。',
        '',
        '## 案例与证据',
        '',
        '- TODO：添加客户案例、研究、资质或第三方验证页面。',
        '',
        '## 文档与资源',
        '',
        '- TODO：添加帮助文档、白皮书、FAQ 与媒体资源页面。',
        '',
        '## 联系方式',
        '',
        '- TODO：补充官方联系页面或公开邮箱。',
        '',
      ].join('\n'),
    });
  }

  return drafts;
}
